name: Sync with Upstream

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync upstream changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add upstream remote
          git remote add upstream https://github.com/meswan-ka/FlowCSSLWC.git
          
          # Fetch upstream
          git fetch upstream
          
          # Merge upstream changes
          git checkout main
          git merge upstream/main --no-edit
          
          # Push to origin
          git push origin main